### ISSUE TITLE
Leading `0x` in private key results in different addresses.

### ISSUE THREAD

**Issue by MicahZoltu** [ethjs/ethjs-account#4]
## Issue Type

- [X] Bug (https://github.com/ethjs/ethjs-sha3/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

The following program spits out two _different_ addresses:
```
import { privateToAccount } from 'ethjs-account';
console.log(JSON.stringify(privateToAccount('ab18faade35ee0c65210782aff7ed995c4cbd351e204e9fe5e4a9caa5fa0dc2b').address));
console.log(JSON.stringify(privateToAccount('0xab18faade35ee0c65210782aff7ed995c4cbd351e204e9fe5e4a9caa5fa0dc2b').address));
```
Output:
```
"0xc2885646840673a2feD7080C29E36555A9F0ACD9"
"0xbC02A3FF56CD1D98197a742A626C4A339F002B8C"
```

# Versions

- Node/NPM: 8.2.1

**Comment by SilentCicero** [comment]
Wow, I'll look into this right away. It should always strip hex prefixes.

**Comment by MicahZoltu** [comment]
I glanced at the code and it definitely looks like it is intending to strip the `0x` so the above two should yield the same result.  I was surprised by the behavior as well.  :)

**Comment by SilentCicero** [comment]
@MicahZoltu holy shit. Thank you so much for finding this. Looks like I had input validation, but it wasn't functioning properly.

Fixed in commit:
https://github.com/ethjs/ethjs-account/commit/e64a68ae6782e4235a38a00d0842e8f2f08fb3f0

Please upgrade to version ethjs-account@0.1.4
